// Signout Constants
export const SIGNOUT = 'SIGNOUT';

// login
export const HANDLE_LOGIN_INPUT_CHANGE = 'HANDLE_LOGIN_INPUT_CHANGE';
export const HANDLE_LOGIN_SUBMIT = 'HANDLE_LOGIN_SUBMIT';
export const SET_ERROR = 'SET_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const ON_LOGIN_SCREEN_FOCUS = 'ON_LOGIN_SCREEN_FOCUS';
// groove sell vendor dashboard
export const SET_GROOVE_SELL_VENDOR_CURRENT_DATE_RANGE =
  'SET_GROOVE_SELL_VENDOR_CURRENT_DATE_RANGE';
export const CURRENT_TAB_SELECTED = 'CURRENT_TAB_SELECTED';
export const SET_BOOL_REVENUE_VIEW = 'SET_BOOL_REVENUE_VIEW';
export const SET_CURRENT_CHART_VALUE = 'SET_CURRENT_CHART_VALUE';
export const FETCH_INITIAL_DATA_SUCCESS = 'FETCH_INITIAL_DATA_SUCCESS';
export const FETCH_INITIAL_DATA = 'FETCH_INITIAL_DATA';
// groove sell vendor transactions
export const FETCH_VENDOR_TRANSACTIONS = 'FETCH_VENDOR_TRANSACTIONS';
export const FETCH_VENDOR_TRANSACTIONS_SUCCESS =
  'FETCH_VENDOR_TRANSACTIONS_SUCCESS';
export const SET_NUM_ROWS_VENDOR_TRANSACTIONS =
  'SET_NUM_ROWS_VENDOR_TRANSACTIONS';
export const SET_DATE_RANGE_VENDOR_TRANSACTIONS =
  'SET_DATE_RANGE_VENDOR_TRANSACTION';
// groove sell affiliate dashboard
export const SET_GROOVE_SELL_AFFILIATE_CURRENT_DATE_RANGE =
  'SET_GROOVE_SELL_AFFILIATE_CURRENT_DATE_RANGE';
export const FETCH_GROOVE_SELL_AFFILIATE_DATA =
  'FETCH_GROOVE_SELL_AFFILIATE_DATA';
export const SET_GROOVE_SELL_AFFILIATE_CURRENT_TAB_SELECTED =
  'SET_GROOVE_SELL_AFFILIATE_CURRENT_TAB_SELECTED';
export const SET_GROOVE_SELL_AFFILIATE_SET_BOOL_REVENUE_VIEW =
  'SET_GROOVE_SELL_AFFILIATE_SET_BOOL_REVENUE_VIEW';
export const SET_GROOVE_SELL_AFFILIATE_SET_CURRENT_CHART_VALUE =
  'SET_GROOVE_SELL_AFFILIATE_SET_CURRENT_CHART_VALUE';
export const FETCH_GROOVE_SELL_AFFILIATE_DATA_SUCCESS =
  'FETCH_GROOVE_SELL_AFFILIATE_DATA_SUCCESS';

// Affiliate transactions
export const FETCH_AFFILIATE_TRANSACTIONS = 'FETCH_AFFILIATE_TRANSACTIONS';
export const FETCH_AFFILIATE_TRANSACTIONS_SUCCESS =
  'FETCH_AFFILIATE_TRANSACTIONS_SUCCESS';
export const SET_NUM_ROWS_AFFILIATE_TRANSACTIONS =
  'SET_NUM_ROWS_AFFILIATE_TRANSACTIONS';
export const SET_DATE_RANGE_AFFILIATE_TRANSACTIONS =
  'SET_DATE_RANGE_AFFILIATE_TRANSACTION';

// Groove Mail List

export const FETCH_GROOVE_MAIL_LIST_DATA_START =
  'FETCH_GROOVE_MAIL_LIST_DATA_START';
export const FETCH_GROOVE_MAIL_LIST_DATA_SUCCESS =
  'FETCH_GROOVE_MAIL_LIST_DATA_SUCCESS';
export const GROOVE_MAIL_SET_DATA = 'GROOVE_MAIL_SET_DATA';

// Groove Mail Forms
export const FETCH_GROOVE_MAIL_FORMS_DATA_START =
  'FETCH_GROOVE_MAIL_FORMS_DATA_START';
export const FETCH_GROOVE_MAIL_FORMS_DATA_SUCCESS =
  'FETCH_GROOVE_MAIL_FORMS_DATA_SUCCESS';
export const GROOVE_MAIL_FORMS_SET_DATA = 'GROOVE_MAIL_FORMS_SET_DATA';

// Groove Mail BroadCast
export const FETCH_GROOVE_MAIL_BROADCAST_DATA_START =
  'FETCH_GROOVE_MAIL_BROADCAST_DATA_START';
export const FETCH_GROOVE_MAIL_BROADCAST_DATA_SUCCESS =
  'FETCH_GROOVE_MAIL_BROADCAST_DATA_SUCCESS';
export const GROOVE_MAIL_BROADCAST_SET_DATA = 'GROOVE_MAIL_BROADCAST_SET_DATA';

export const GROOVE_MAIL_STOP_CAMPAIGN_BROADCAST =
  'GROOVE_MAIL_STOP_CAMPAIGN_BROADCAST';

export const GROOVE_MAIL_STOP_CAMPAIGN_BROADCAST_SUCCESS =
  'GROOVE_MAIL_STOP_CAMPAIGN_BROADCAST_SUCCESS';

export const GROOVE_MAIL_SEND_NOW_BROADCAST = 'GROOVE_MAIL_SEND_NOW_BROADCAST';
export const GROOVE_MAIL_SEND_NOW_BROADCAST_SUCCESS =
  'GROOVE_MAIL_SEND_NOW_BROADCAST_SUCCESS';

// Groove Mail Dashboard

export const SET_GROOVE_MAIL_DASHBOARD_CURRENT_DATE_RANGE =
  'SET_GROOVE_MAIL_DASHBOARD_CURRENT_DATE_RANGE';
export const GROOVE_MAIL_DASHBOARD_CURRENT_TAB_SELECTED =
  'GROOVE_MAIL_DASHBOARD_CURRENT_TAB_SELECTED';
export const GROOVE_MAIL_DASHBOARD_SET_CURRENT_CHART_VALUE =
  'GROOVE_MAIL_DASHBOARD_SET_CURRENT_CHART_VALUE';
export const GROOVE_MAIL_DASHBOARD_FETCH_INITIAL_DATA_SUCCESS =
  'GROOVE_MAIL_DASHBOARD_FETCH_INITIAL_DATA_SUCCESS';
export const GROOVE_MAIL_DASHBOARD_FETCH_INITIAL_DATA =
  'GROOVE_MAIL_DASHBOARD_FETCH_INITIAL_DATA';

// Groove Video Dashboard
export const SET_GROOVE_VIDEO_DASHBOARD_CURRENT_DATE_RANGE =
  'SET_GROOVE_VIDEO_DASHBOARD_CURRENT_DATE_RANGE';
export const GROOVE_VIDEO_DASHBOARD_SET_CURRENT_CHART_VALUE =
  'GROOVE_VIDEO_DASHBOARD_SET_CURRENT_CHART_VALUE';
export const GROOVE_VIDEO_DASHBOARD_FETCH_INITIAL_DATA_SUCCESS =
  'GROOVE_VIDEO_DASHBOARD_FETCH_INITIAL_DATA_SUCCESS';
export const GROOVE_VIDEO_DASHBOARD_FETCH_INITIAL_DATA =
  'GROOVE_VIDEO_DASHBOARD_FETCH_INITIAL_DATA';

// Groove Video Analytics
export const FETCH_GROOVE_VIDEO_ANALYTICS_DATA_START =
  'FETCH_GROOVE_VIDEO_ANALYTICS_DATA_START';
export const FETCH_GROOVE_VIDEO_ANALYTICS_DATA_SUCCESS =
  'FETCH_GROOVE_VIDEO_ANALYTICS_DATA_SUCCESS';
export const GROOVE_VIDEO_ANALYTICS_SET_DATA =
  'GROOVE_VIDEO_ANALYTICS_SET_DATA';

// Groove Video Analytics
export const FETCH_GROOVE_MEMBER_ANALYTICS_DATA =
  'FETCH_GROOVE_MEMBER_ANALYTICS_DATA';
export const FETCH_GROOVE_MEMBER_ANALYTICS_DATA_SUCCESS =
  'FETCH_GROOVE_MEMBER_ANALYTICS_DATA_SUCCESS';
export const SET_GROOVE_MEMBER_CURRENT_DATE_RANGE =
  'SET_GROOVE_MEMBER_CURRENT_DATE_RANGE';

// Groove Pages Analytics

export const FETCH_GROOVE_PAGES_ANALYTICS_DATA =
  'FETCH_GROOVE_PAGES_ANALYTICS_DATA';
export const FETCH_GROOVE_PAGES_ANALYTICS_DATA_SUCCESS =
  'FETCH_GROOVE_PAGES_ANALYTICS_DATA_SUCCESS';
export const SET_GROOVE_PAGES_CURRENT_DATE_RANGE =
  'SET_GROOVE_PAGES_CURRENT_DATE_RANGE';
